### ISSUE TITLE
Set login/password

### ISSUE THREAD

**Issue by aguinaldoabbj** [tig/ArduinoShell#1]
Hi,

I've been testing both your code and the code you forked from and I wasn't able to find where users and passwords are defined. I cant get to the prompt asking for login/password. Could you please clarify where those credentials are set?

Thanks in advance.

**Comment by tig** [comment]
Sorry, but the way I use it has no auth, so I have no idea! 

I suspect you'll need to respond to the auth prompt with your own code.

**Comment by aguinaldoabbj** [comment]
> Sorry, but the way I use it has no auth, so I have no idea!
> 
> I suspect you'll need to respond to the auth prompt with your own code.

I've just found out in the original code. There is a default function for handling credentials in Shell.cpp, default user/password are hardcoded there.

**Comment by tig** [comment]
Excellent!

**Comment by aguinaldoabbj** [comment]
@tig Sorry to recall to this. Have you figured out how to disable echoing?
